version: '2.4'

services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 10g
    volumes:
      - ~/.modal.toml:/root/.modal.toml:ro

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest /root/test.py